name: Fetchin build CI

on: 
  push:
    branches: [ release ]
  pull_request: 
    branches: [ release ]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.6.0
      
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Publish to NPM
        run: pnpm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}